### ISSUE TITLE
dependency

### ISSUE THREAD

**Issue by benkeser** [cxthyngxy/finalproj4#1]
please remove dependency in Makefile of your report on `project_image`. I do not want to rebuild your project image locally. I will re-grade when this issue is closed.

**Comment by cxthyngxy** [comment]
Hi Professor Benkeser,

Are you referring to the "Dockerfile" dependency in the rule?

**Comment by benkeser** [comment]
[this line](https://github.com/cxthyngxy/finalproj4/blob/ac1dc3bf056970283aa68f1e383209e0ad2591de/Makefile#L21)

**Comment by cxthyngxy** [comment]
resolved and re-pushed!

**Comment by cxthyngxy** [comment]
thank you!
